### PR TITLE
Remove `\X` characters in character ranges for url regex.

### LINKED ISSUE #9: Does not compile on Elixir 1.4.4/OTP 20 RC-2
## Version info (ouput of `elixir --version`) ##
```
Erlang/OTP 20 [RELEASE CANDIDATE 2] [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.4.4
```

## Error running `mix test` ##
```
== Compilation error on file lib/validator.ex ==
** (Regex.CompileError) invalid range in character class at position 320
    (elixir) lib/regex.ex:171: Regex.compile!/2
    (elixir) expanding macro: Kernel.sigil_r/2
    lib/validator.ex:6: Validator (module)
    (elixir) expanding macro: Kernel.@/1
    lib/validator.ex:6: Validator (module)
```

I'll update this ticket as I go along debugging it and submitting a PR.

### PR DESCRIPTION
**Pull request by awochna**
This might not be the right course of action, but removing them gets all
tests to pass. If this is wrong, it implies that the tests are not yet
comprehensive enough, but then again, regex tests almost can't be.

In the original regex set linked to from the documentation
(https://gist.github.com/dperini/729294), these characters are unicode
characters like `\u00a1`. I haven't been able to find the equivalent in
my searches for regex characters in elixir beginning with a `\X`. I'm
sure it also makes for poor search queries.

Closes #9 

If someone knows how I can rewrite this to properly use `\X`, please let me know and I will.

### CODE REVIEW

**Comment by awochna** [comment]
This is still a work in progress as I'm trying to add unicode character matching to urls (including tests) in a way that compiles on Elixir 1.4.4/OTP 20 RC2.

**Comment by awochna** [comment]
Closing this to create a cleaner pull request.
