### ISSUE TITLE
Does not compile on Elixir 1.4.4/OTP 20 RC-2

### ISSUE THREAD

**Issue by awochna** [fourkio/validator#9]
## Version info (ouput of `elixir --version`) ##
```
Erlang/OTP 20 [RELEASE CANDIDATE 2] [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.4.4
```

## Error running `mix test` ##
```
== Compilation error on file lib/validator.ex ==
** (Regex.CompileError) invalid range in character class at position 320
    (elixir) lib/regex.ex:171: Regex.compile!/2
    (elixir) expanding macro: Kernel.sigil_r/2
    lib/validator.ex:6: Validator (module)
    (elixir) expanding macro: Kernel.@/1
    lib/validator.ex:6: Validator (module)
```

I'll update this ticket as I go along debugging it and submitting a PR.
